### ISSUE TITLE
Edit menu not visible when there is a cover available (pickles4evaaaa/mybibliotheca:2.0.1)

### ISSUE THREAD

**Issue by RMENANT** [pickles4evaaaa/mybibliotheca#118]
Hi
When using MyBibliotheca on my phone (Android 15), I can’t access the database editing menu because it’s hidden behind the book cover.
Could you fix this so the menu becomes accessible on mobile?
Peharps by resizing the cover ?

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/c4f3a230-df98-4491-b127-f4708e0f80aa" />

Thank you for for this great job

**Comment by pickles4evaaaa** [comment]
<img width="602" height="861" alt="Image" src="https://github.com/user-attachments/assets/ba2376ae-e652-473d-8f97-d1fc81c4b7a1" />

I just pushed an update that will be added to the 'beta-latest' tag
As far as I can see on my side of things, it is working as expected

**Comment by RMENANT** [comment]
Thank you 
I made a new built with latest (following the footpage - it seems right)
<img width="270" height="585" alt="Image" src="https://github.com/user-attachments/assets/e10d10c1-fede-49d6-9dbb-e36bd0bec895" />

But i still have a partly hidden menu
I don't understand why (Using Firefox)
<img width="270" height="585" alt="Image" src="https://github.com/user-attachments/assets/d8bfaada-2862-4ef0-8dd5-dd42d93054c4" />

Same problem on Chrome ...

**Comment by pickles4evaaaa** [comment]
> Thank you I made a new built with latest (following the footpage - it seems right) <img alt="Image" width="270" height="585" src="https://private-user-images.githubusercontent.com/186338/514917952-e10d10c1-fede-49d6-9dbb-e36bd0bec895.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MDA5ODYsIm5iZiI6MTc2MzQwMDY4NiwicGF0aCI6Ii8xODYzMzgvNTE0OTE3OTUyLWUxMGQxMGMxLWZlZGUtNDlkNi05ZGJiLWUzNmJkMGJlYzg5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExN1QxNzMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTIzODRlZDZmMjhkYWM1YmE1NzFiY2U0OGYwOTZlODRjZDNlMmNlMTA3MWNjOWNiYzNjOGU2MjU5OWJlYWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.96f93-AERSzPZIIplPcWaNtGbAhApQnNXEmT-7AaGsM">
> 
> But i still have a partly hidden menu I don't understand why (Using Firefox) <img alt="Image" width="270" height="585" src="https://private-user-images.githubusercontent.com/186338/514918060-d8bfaada-2862-4ef0-8dd5-dd42d93054c4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MDA5ODYsIm5iZiI6MTc2MzQwMDY4NiwicGF0aCI6Ii8xODYzMzgvNTE0OTE4MDYwLWQ4YmZhYWRhLTI4NjItNGVmMC04ZGQ1LWRkNDJkOTMwNTRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExN1QxNzMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGZiMDQzM2QyYTRmZDI2MzAxMTk0MzVmZjQ4N2Y0MmE0NTQ1ZDlkZjE0NWQwMTZlZDk1ODg4N2IwMWY0YzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T953rR1mzKASzpuAYa2xCe5ZSXlmLaOLZG-7l-IlEiQ">
> 
> Same problem on Chrome ...

I did not push an update to the latest tag at the time that you were testing. 

I have just pushed the 'beta-latest' tag, so please give that a shot and let me know if the issue is fixed.

**Comment by RMENANT** [comment]
Wasn't abke to test before.
It works !
Thank you very much !
Continue testing with local AI

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/c3638a33-2289-4e41-af8e-28ee4226318e" />
